using Checkmate.Entity;
using Checkmate.Utils;
using Microsoft.EntityFrameworkCore;

namespace Checkmate
{
    public class Chesscontext(DbContextOptions options) : DbContext(options)
    {
        public DbSet<User> Users { get; set; }
        public DbSet<Tournament> Tournaments { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {           
#if DEBUG

            
            modelBuilder.Entity<User>().HasData([
                new User { Id = 21, Username = "Nico", Email = "nico@chess.com", Password = "123456", Birthdate = new DateTime(1990, 11, 30), Genre = User.GenreType.Male, Elo = 2859, Role = User.RoleType.Admin },
                new User { Id = 1, Username = "MagnusCarlsen", Email = "magnus@chess.com", Password = "123456", Birthdate = new DateTime(1990, 11, 30), Genre = User.GenreType.Male, Elo = 2859, Role = User.RoleType.Player },
                new User { Id = 2, Username = "HikaruNakamura", Email = "hikaru@chess.com", Password = "123456", Birthdate = new DateTime(1987, 12, 9), Genre = User.GenreType.Male, Elo = 2787, Role = User.RoleType.Player },
                new User { Id = 3, Username = "DingLiren", Email = "ding@chess.com", Password = "123456", Birthdate = new DateTime(1992, 10, 24), Genre = User.GenreType.Male, Elo = 2780, Role = User.RoleType.Player },
                new User { Id = 4, Username = "IanNepomniachtchi", Email = "nepo@chess.com", Password = "123456", Birthdate = new DateTime(1990, 7, 14), Genre = User.GenreType.Male, Elo = 2770, Role = User.RoleType.Player },
                new User { Id = 5, Username = "FabianoCaruana", Email = "fabiano@chess.com", Password = "123456", Birthdate = new DateTime(1992, 7, 30), Genre = User.GenreType.Male, Elo = 2760, Role = User.RoleType.Player },
                new User { Id = 6, Username = "AlirezaFirouzja", Email = "firouzja@chess.com", Password = "123456", Birthdate = new DateTime(2003, 6, 18), Genre = User.GenreType.Male, Elo = 2750, Role = User.RoleType.Player },
                new User { Id = 7, Username = "JuditPolgar", Email = "judit@chess.com", Password = "123456", Birthdate = new DateTime(1976, 7, 23), Genre = User.GenreType.Female, Elo = 2735, Role = User.RoleType.Player },
                new User { Id = 8, Username = "HouYifan", Email = "hou@chess.com", Password = "123456", Birthdate = new DateTime(1994, 2, 27), Genre = User.GenreType.Female, Elo = 2658, Role = User.RoleType.Player },
                new User { Id = 9, Username = "BobbyFischer", Email = "fischer@chess.com", Password = "123456", Birthdate = new DateTime(1943, 3, 9), Genre = User.GenreType.Male, Elo = 2785, Role = User.RoleType.Player },
                new User { Id = 10, Username = "GarryKasparov", Email = "kasparov@chess.com", Password = "123456", Birthdate = new DateTime(1963, 4, 13), Genre = User.GenreType.Male, Elo = 2812, Role = User.RoleType.Player },               
                new User { Id = 11, Username = "ChessMaster42", Email = "cm42@chess.com", Password = "123456", Birthdate = new DateTime(1995, 5, 15), Genre = User.GenreType.Other, Elo = 2100, Role = User.RoleType.Player },
                new User { Id = 12, Username = "KnightRider", Email = "knight@chess.com", Password = "123456", Birthdate = new DateTime(1988, 8, 8), Genre = User.GenreType.Male, Elo = 1800, Role = User.RoleType.Player },
                new User { Id = 13, Username = "QueenSlayer", Email = "queen@chess.com", Password = "123456", Birthdate = new DateTime(1999, 12, 25), Genre = User.GenreType.Female, Elo = 1950, Role = User.RoleType.Player },
                new User { Id = 14, Username = "PawnStar", Email = "pawn@chess.com", Password = "123456", Birthdate = new DateTime(2000, 1, 1), Genre = User.GenreType.Male, Elo = 1200, Role = User.RoleType.Player },
                new User { Id = 15, Username = "RookAndRoll", Email = "rook@chess.com", Password = "123456", Birthdate = new DateTime(1993, 3, 3), Genre = User.GenreType.Other, Elo = 1600, Role = User.RoleType.Player },
                new User { Id = 16, Username = "TheStrategist", Email = "strategist@chess.com", Password = "123456", Birthdate = new DateTime(1985, 7, 7), Genre = User.GenreType.Male, Elo = 2000, Role = User.RoleType.Player },
                new User { Id = 17, Username = "BlitzQueen", Email = "blitz@chess.com", Password = "123456", Birthdate = new DateTime(1997, 6, 21), Genre = User.GenreType.Female, Elo = 1750, Role = User.RoleType.Player },
                new User { Id = 18, Username = "CheckmateKing", Email = "checkmate@chess.com", Password = "123456", Birthdate = new DateTime(1980, 11, 11), Genre = User.GenreType.Male, Elo = 2200, Role = User.RoleType.Player },
                new User { Id = 19, Username = "EndgameWizard", Email = "endgame@chess.com", Password = "123456", Birthdate = new DateTime(1992, 2, 2), Genre = User.GenreType.Male, Elo = 2300, Role = User.RoleType.Player },
                new User { Id = 20, Username = "OpeningGenius", Email = "opening@chess.com", Password = "123456", Birthdate = new DateTime(1998, 9, 9), Genre = User.GenreType.Other, Elo = 1900, Role = User.RoleType.Player },
                new User { Id = 22, Username = "AlexMartin", Email = "alex.martin22@gmail.com", Password = "pwd4821", Birthdate = new DateTime(1991, 4, 12), Genre = User.GenreType.Male, Elo = 1620, Role = User.RoleType.Player },
                new User { Id = 23, Username = "SamGarcia", Email = "sam.garcia7@yahoo.com", Password = "pwd3012", Birthdate = new DateTime(1986, 8, 3), Genre = User.GenreType.Other, Elo = 1475, Role = User.RoleType.Player },
                new User { Id = 24, Username = "TaylorLopez", Email = "taylor.lopez13@outlook.com", Password = "pwd6543", Birthdate = new DateTime(1999, 2, 28), Genre = User.GenreType.Female, Elo = 1540, Role = User.RoleType.Player },
                new User { Id = 25, Username = "JordanJohnson", Email = "jordan.johnson41@example.com", Password = "pwd7730", Birthdate = new DateTime(1979, 12, 1), Genre = User.GenreType.Male, Elo = 1825, Role = User.RoleType.Player },
                new User { Id = 26, Username = "MorganSmith", Email = "morgan.smith5@mail.com", Password = "pwd1904", Birthdate = new DateTime(2002, 6, 15), Genre = User.GenreType.Female, Elo = 1360, Role = User.RoleType.Player },
                new User { Id = 27, Username = "CaseyBrown", Email = "casey.brown99@protonmail.com", Password = "pwd5882", Birthdate = new DateTime(1983, 11, 29), Genre = User.GenreType.Other, Elo = 1588, Role = User.RoleType.Player },
                new User { Id = 28, Username = "DrewWilliams", Email = "drew.williams8@hotmail.com", Password = "pwd4127", Birthdate = new DateTime(1994, 5, 20), Genre = User.GenreType.Male, Elo = 1710, Role = User.RoleType.Player },
                new User { Id = 29, Username = "EvelynJones", Email = "evelyn.jones2@gamesmail.com", Password = "pwd2256", Birthdate = new DateTime(1996, 9, 9), Genre = User.GenreType.Female, Elo = 1395, Role = User.RoleType.Player },
                new User { Id = 30, Username = "LiamMiller", Email = "liam.miller17@playzone.net", Password = "pwd8341", Birthdate = new DateTime(1990, 3, 30), Genre = User.GenreType.Male, Elo = 1987, Role = User.RoleType.Player },
                new User { Id = 31, Username = "NoahDavis", Email = "noah.davis4@chessworld.org", Password = "pwd0192", Birthdate = new DateTime(2001, 1, 18), Genre = User.GenreType.Male, Elo = 1280, Role = User.RoleType.Player },
                new User { Id = 32, Username = "OliverWilson", Email = "oliver.wilson61@boardgames.io", Password = "pwd7723", Birthdate = new DateTime(1987, 10, 5), Genre = User.GenreType.Male, Elo = 2035, Role = User.RoleType.Player },
                new User { Id = 33, Username = "ElijahAnderson", Email = "elijah.anderson12@strategy.gg", Password = "pwd9406", Birthdate = new DateTime(1998, 7, 7), Genre = User.GenreType.Male, Elo = 1762, Role = User.RoleType.Player },
                new User { Id = 34, Username = "JamesThomas", Email = "james.thomas3@gmail.com", Password = "pwd2675", Birthdate = new DateTime(1975, 2, 14), Genre = User.GenreType.Male, Elo = 2100, Role = User.RoleType.Player },
                new User { Id = 35, Username = "BenjaminTaylor", Email = "benjamin.taylor88@yahoo.com", Password = "pwd3819", Birthdate = new DateTime(1993, 6, 2), Genre = User.GenreType.Male, Elo = 1427, Role = User.RoleType.Player },
                new User { Id = 36, Username = "LucasMoore", Email = "lucas.moore47@outlook.com", Password = "pwd6654", Birthdate = new DateTime(1989, 4, 23), Genre = User.GenreType.Male, Elo = 1674, Role = User.RoleType.Player },
                new User { Id = 37, Username = "MasonJackson", Email = "mason.jackson20@example.com", Password = "pwd5580", Birthdate = new DateTime(1997, 11, 11), Genre = User.GenreType.Male, Elo = 1511, Role = User.RoleType.Player },
                new User { Id = 38, Username = "LoganWhite", Email = "logan.white66@mail.com", Password = "pwd1033", Birthdate = new DateTime(1995, 8, 24), Genre = User.GenreType.Other, Elo = 1799, Role = User.RoleType.Player },
                new User { Id = 39, Username = "EthanHarris", Email = "ethan.harris13@protonmail.com", Password = "pwd4545", Birthdate = new DateTime(1984, 12, 6), Genre = User.GenreType.Male, Elo = 1865, Role = User.RoleType.Player },
                new User { Id = 40, Username = "AvaThompson", Email = "ava.thompson31@hotmail.com", Password = "pwd2880", Birthdate = new DateTime(2000, 5, 4), Genre = User.GenreType.Female, Elo = 1322, Role = User.RoleType.Player },
                new User { Id = 41, Username = "SophiaMartinez", Email = "sophia.martinez55@gamesmail.com", Password = "pwd7201", Birthdate = new DateTime(1992, 9, 14), Genre = User.GenreType.Female, Elo = 1703, Role = User.RoleType.Player },
                new User { Id = 42, Username = "IsabellaRobinson", Email = "isabella.robinson9@playzone.net", Password = "pwd4419", Birthdate = new DateTime(1994, 3, 2), Genre = User.GenreType.Female, Elo = 1609, Role = User.RoleType.Player },
                new User { Id = 43, Username = "MiaClark", Email = "mia.clark77@chessworld.org", Password = "pwd5310", Birthdate = new DateTime(2003, 10, 21), Genre = User.GenreType.Female, Elo = 1199, Role = User.RoleType.Player },
                new User { Id = 44, Username = "AmeliaRodriguez", Email = "amelia.rodriguez2@boardgames.io", Password = "pwd6752", Birthdate = new DateTime(1982, 1, 27), Genre = User.GenreType.Female, Elo = 1890, Role = User.RoleType.Player },
                new User { Id = 45, Username = "HarperLewis", Email = "harper.lewis14@strategy.gg", Password = "pwd9944", Birthdate = new DateTime(1990, 6, 6), Genre = User.GenreType.Other, Elo = 1555, Role = User.RoleType.Player },
                new User { Id = 46, Username = "CharlotteLee", Email = "charlotte.lee5@gmail.com", Password = "pwd2168", Birthdate = new DateTime(1988, 2, 8), Genre = User.GenreType.Female, Elo = 2001, Role = User.RoleType.Player },
                new User { Id = 47, Username = "ZoeyWalker", Email = "zoey.walker42@yahoo.com", Password = "pwd3478", Birthdate = new DateTime(1996, 12, 19), Genre = User.GenreType.Female, Elo = 1448, Role = User.RoleType.Player },
                new User { Id = 48, Username = "GraceHall", Email = "grace.hall23@outlook.com", Password = "pwd8110", Birthdate = new DateTime(1981, 7, 3), Genre = User.GenreType.Female, Elo = 2160, Role = User.RoleType.Player },
                new User { Id = 49, Username = "LunaAllen", Email = "luna.allen90@example.com", Password = "pwd9722", Birthdate = new DateTime(2004, 11, 2), Genre = User.GenreType.Female, Elo = 1015, Role = User.RoleType.Player },
                new User { Id = 50, Username = "CamilaYoung", Email = "camila.young58@mail.com", Password = "pwd1567", Birthdate = new DateTime(1999, 4, 10), Genre = User.GenreType.Female, Elo = 1491, Role = User.RoleType.Player },
                new User { Id = 51, Username = "AriaKing", Email = "aria.king6@protonmail.com", Password = "pwd6633", Birthdate = new DateTime(1997, 9, 25), Genre = User.GenreType.Female, Elo = 1734, Role = User.RoleType.Player },
                new User { Id = 52, Username = "EllaWright", Email = "ella.wright1@hotmail.com", Password = "pwd4870", Birthdate = new DateTime(1993, 3, 16), Genre = User.GenreType.Female, Elo = 1452, Role = User.RoleType.Player },
                new User { Id = 53, Username = "ScarlettScott", Email = "scarlett.scott33@gamesmail.com", Password = "pwd3355", Birthdate = new DateTime(1985, 8, 29), Genre = User.GenreType.Female, Elo = 1996, Role = User.RoleType.Player },
                new User { Id = 54, Username = "VictoriaTorres", Email = "victoria.torres71@playzone.net", Password = "pwd9087", Birthdate = new DateTime(1991, 10, 17), Genre = User.GenreType.Female, Elo = 1768, Role = User.RoleType.Player },
                new User { Id = 55, Username = "RileyNguyen", Email = "riley.nguyen44@chessworld.org", Password = "pwd2299", Birthdate = new DateTime(2000, 2, 4), Genre = User.GenreType.Other, Elo = 1376, Role = User.RoleType.Player },
                new User { Id = 56, Username = "NoraHill", Email = "nora.hill18@boardgames.io", Password = "pwd5501", Birthdate = new DateTime(1980, 5, 13), Genre = User.GenreType.Female, Elo = 2112, Role = User.RoleType.Player },
                new User { Id = 57, Username = "HazelFlores", Email = "hazel.flores8@strategy.gg", Password = "pwd7812", Birthdate = new DateTime(1992, 1, 5), Genre = User.GenreType.Female, Elo = 1681, Role = User.RoleType.Player },
                new User { Id = 58, Username = "ChloeGreen", Email = "chloe.green69@gmail.com", Password = "pwd0049", Birthdate = new DateTime(1998, 7, 31), Genre = User.GenreType.Female, Elo = 1523, Role = User.RoleType.Player },
                new User { Id = 59, Username = "LilyAdams", Email = "lily.adams27@yahoo.com", Password = "pwd2783", Birthdate = new DateTime(1996, 9, 6), Genre = User.GenreType.Female, Elo = 1407, Role = User.RoleType.Player },
                new User { Id = 60, Username = "PenelopeNelson", Email = "penelope.nelson3@outlook.com", Password = "pwd6195", Birthdate = new DateTime(1987, 6, 26), Genre = User.GenreType.Female, Elo = 1837, Role = User.RoleType.Player },
                new User { Id = 61, Username = "LaylaBaker", Email = "layla.baker52@example.com", Password = "pwd8320", Birthdate = new DateTime(2005, 12, 12), Genre = User.GenreType.Female, Elo = 925, Role = User.RoleType.Player },
                new User { Id = 62, Username = "ZoeHernandez", Email = "zoe.hernandez29@mail.com", Password = "pwd1436", Birthdate = new DateTime(1994, 11, 8), Genre = User.GenreType.Female, Elo = 1570, Role = User.RoleType.Player },
                new User { Id = 63, Username = "LaylaRivera", Email = "layla.rivera64@protonmail.com", Password = "pwd9902", Birthdate = new DateTime(1990, 3, 1), Genre = User.GenreType.Other, Elo = 1908, Role = User.RoleType.Player },
                new User { Id = 64, Username = "CamilaCampbell", Email = "camila.campbell11@hotmail.com", Password = "pwd4646", Birthdate = new DateTime(1989, 10, 30), Genre = User.GenreType.Female, Elo = 1775, Role = User.RoleType.Player },
                new User { Id = 65, Username = "EllaMitchell", Email = "ella.mitchell39@gamesmail.com", Password = "pwd2057", Birthdate = new DateTime(1995, 7, 2), Genre = User.GenreType.Female, Elo = 1328, Role = User.RoleType.Player },
                new User { Id = 66, Username = "LiamCarter", Email = "liam.carter72@playzone.net", Password = "pwd7129", Birthdate = new DateTime(1992, 4, 28), Genre = User.GenreType.Male, Elo = 1897, Role = User.RoleType.Player },
                new User { Id = 67, Username = "NoahRoberts", Email = "noah.roberts45@chessworld.org", Password = "pwd3771", Birthdate = new DateTime(1986, 1, 21), Genre = User.GenreType.Male, Elo = 2050, Role = User.RoleType.Player },
                new User { Id = 68, Username = "OliverPerez", Email = "oliver.perez9@boardgames.io", Password = "pwd5566", Birthdate = new DateTime(2001, 8, 16), Genre = User.GenreType.Male, Elo = 1215, Role = User.RoleType.Player },
                new User { Id = 69, Username = "ElijahCollins", Email = "elijah.collins23@strategy.gg", Password = "pwd8460", Birthdate = new DateTime(1999, 5, 9), Genre = User.GenreType.Male, Elo = 1504, Role = User.RoleType.Player },
                new User { Id = 70, Username = "JamesStewart", Email = "james.stewart2@gmail.com", Password = "pwd3918", Birthdate = new DateTime(1984, 9, 12), Genre = User.GenreType.Male, Elo = 2228, Role = User.RoleType.Player },
                new User { Id = 71, Username = "BenjaminMorris", Email = "benjamin.morris14@yahoo.com", Password = "pwd2734", Birthdate = new DateTime(1991, 2, 6), Genre = User.GenreType.Male, Elo = 1637, Role = User.RoleType.Player },
                new User { Id = 72, Username = "LucasRogers", Email = "lucas.rogers57@outlook.com", Password = "pwd6032", Birthdate = new DateTime(1988, 11, 4), Genre = User.GenreType.Male, Elo = 1748, Role = User.RoleType.Player },
                new User { Id = 73, Username = "MasonReed", Email = "mason.reed81@example.com", Password = "pwd4859", Birthdate = new DateTime(1996, 6, 18), Genre = User.GenreType.Male, Elo = 1416, Role = User.RoleType.Player },
                new User { Id = 74, Username = "LoganCook", Email = "logan.cook33@mail.com", Password = "pwd9220", Birthdate = new DateTime(1990, 10, 2), Genre = User.GenreType.Male, Elo = 1979, Role = User.RoleType.Player },
                new User { Id = 75, Username = "EthanBell", Email = "ethan.bell28@protonmail.com", Password = "pwd1582", Birthdate = new DateTime(1982, 7, 14), Genre = User.GenreType.Male, Elo = 2093, Role = User.RoleType.Player },
                new User { Id = 76, Username = "AvaMurphy", Email = "ava.murphy46@hotmail.com", Password = "pwd3376", Birthdate = new DateTime(1997, 9, 27), Genre = User.GenreType.Female, Elo = 1345, Role = User.RoleType.Player },
                new User { Id = 77, Username = "SophiaBailey", Email = "sophia.bailey60@gamesmail.com", Password = "pwd7641", Birthdate = new DateTime(1993, 1, 19), Genre = User.GenreType.Female, Elo = 1707, Role = User.RoleType.Player },
                new User { Id = 78, Username = "IsabellaRivera", Email = "isabella.rivera38@playzone.net", Password = "pwd0584", Birthdate = new DateTime(1990, 12, 8), Genre = User.GenreType.Female, Elo = 1881, Role = User.RoleType.Player },
                new User { Id = 79, Username = "MiaCooper", Email = "mia.cooper5@chessworld.org", Password = "pwd4810", Birthdate = new DateTime(2002, 3, 7), Genre = User.GenreType.Female, Elo = 1247, Role = User.RoleType.Player },
                new User { Id = 80, Username = "AmeliaPeterson", Email = "amelia.peterson70@boardgames.io", Password = "pwd9123", Birthdate = new DateTime(1985, 5, 29), Genre = User.GenreType.Female, Elo = 2017, Role = User.RoleType.Player },
                new User { Id = 81, Username = "HarperGray", Email = "harper.gray26@strategy.gg", Password = "pwd6408", Birthdate = new DateTime(1998, 11, 20), Genre = User.GenreType.Other, Elo = 1399, Role = User.RoleType.Player },
                new User { Id = 82, Username = "CharlotteJames", Email = "charlotte.james2@gmail.com", Password = "pwd2841", Birthdate = new DateTime(1994, 2, 11), Genre = User.GenreType.Female, Elo = 1669, Role = User.RoleType.Player },
                new User { Id = 83, Username = "ZoeyWatson", Email = "zoey.watson49@yahoo.com", Password = "pwd5027", Birthdate = new DateTime(2000, 7, 23), Genre = User.GenreType.Female, Elo = 1256, Role = User.RoleType.Player },
                new User { Id = 84, Username = "GraceBrooks", Email = "grace.brooks31@outlook.com", Password = "pwd7789", Birthdate = new DateTime(1986, 1, 30), Genre = User.GenreType.Female, Elo = 1872, Role = User.RoleType.Player },
                new User { Id = 85, Username = "LunaKelly", Email = "luna.kelly8@example.com", Password = "pwd3902", Birthdate = new DateTime(2004, 9, 4), Genre = User.GenreType.Female, Elo = 968, Role = User.RoleType.Player },
                new User { Id = 86, Username = "CamilaSanders", Email = "camila.sanders12@mail.com", Password = "pwd1478", Birthdate = new DateTime(1991, 6, 9), Genre = User.GenreType.Female, Elo = 1530, Role = User.RoleType.Player },
                new User { Id = 87, Username = "AriaPrice", Email = "aria.price56@protonmail.com", Password = "pwd5514", Birthdate = new DateTime(1997, 4, 1), Genre = User.GenreType.Female, Elo = 1694, Role = User.RoleType.Player },
                new User { Id = 88, Username = "EllaBennett", Email = "ella.bennett95@hotmail.com", Password = "pwd8686", Birthdate = new DateTime(1995, 8, 13), Genre = User.GenreType.Female, Elo = 1482, Role = User.RoleType.Player },
                new User { Id = 89, Username = "ScarlettGray", Email = "scarlett.gray21@gamesmail.com", Password = "pwd3244", Birthdate = new DateTime(1983, 10, 10), Genre = User.GenreType.Female, Elo = 2039, Role = User.RoleType.Player },
                new User { Id = 90, Username = "VictoriaRussell", Email = "victoria.russell7@playzone.net", Password = "pwd7011", Birthdate = new DateTime(1992, 11, 15), Genre = User.GenreType.Female, Elo = 1759, Role = User.RoleType.Player },
                new User { Id = 91, Username = "RileyOrtiz", Email = "riley.ortiz40@chessworld.org", Password = "pwd4398", Birthdate = new DateTime(1999, 2, 2), Genre = User.GenreType.Other, Elo = 1369, Role = User.RoleType.Player },
                new User { Id = 92, Username = "NoraGutierrez", Email = "nora.gutierrez6@boardgames.io", Password = "pwd9555", Birthdate = new DateTime(1981, 3, 25), Genre = User.GenreType.Female, Elo = 2144, Role = User.RoleType.Player },
                new User { Id = 93, Username = "HazelRamirez", Email = "hazel.ramirez63@strategy.gg", Password = "pwd2689", Birthdate = new DateTime(1993, 12, 5), Genre = User.GenreType.Female, Elo = 1716, Role = User.RoleType.Player },
                new User { Id = 94, Username = "ChloeWatkins", Email = "chloe.watkins19@gmail.com", Password = "pwd3840", Birthdate = new DateTime(1996, 6, 30), Genre = User.GenreType.Female, Elo = 1526, Role = User.RoleType.Player },
                new User { Id = 95, Username = "LilyWebb", Email = "lily.webb85@yahoo.com", Password = "pwd4751", Birthdate = new DateTime(1998, 5, 17), Genre = User.GenreType.Female, Elo = 1410, Role = User.RoleType.Player },
                new User { Id = 96, Username = "PenelopeSantos", Email = "penelope.santos34@outlook.com", Password = "pwd8920", Birthdate = new DateTime(1989, 9, 1), Genre = User.GenreType.Female, Elo = 1850, Role = User.RoleType.Player },
                new User { Id = 97, Username = "LaylaPerry", Email = "layla.perry24@example.com", Password = "pwd6147", Birthdate = new DateTime(2005, 2, 28), Genre = User.GenreType.Female, Elo = 908, Role = User.RoleType.Player },
                new User { Id = 98, Username = "ZoePowell", Email = "zoe.powell2@mail.com", Password = "pwd7563", Birthdate = new DateTime(1994, 7, 6), Genre = User.GenreType.Female, Elo = 1569, Role = User.RoleType.Player },
                new User { Id = 99, Username = "AlexLong", Email = "alex.long67@protonmail.com", Password = "pwd0825", Birthdate = new DateTime(1990, 10, 20), Genre = User.GenreType.Male, Elo = 1914, Role = User.RoleType.Player },
                new User { Id = 100, Username = "CaseyPatterson", Email = "casey.patterson44@hotmail.com", Password = "pwd4991", Birthdate = new DateTime(1987, 1, 7), Genre = User.GenreType.Other, Elo = 1602, Role = User.RoleType.Player },
                new User { Id = 101, Username = "DrewReynolds", Email = "drew.reynolds38@gamesmail.com", Password = "pwd1338", Birthdate = new DateTime(1992, 11, 26), Genre = User.GenreType.Male, Elo = 1771, Role = User.RoleType.Player },
                new User { Id = 102, Username = "NoahFisher", Email = "noah.fisher10@playzone.net", Password = "pwd2886", Birthdate = new DateTime(1996, 8, 14), Genre = User.GenreType.Male, Elo = 1497, Role = User.RoleType.Player },
                new User { Id = 103, Username = "IsabellaBaker", Email = "isabella.baker55@chessworld.org", Password = "pwd5511", Birthdate = new DateTime(1991, 3, 3), Genre = User.GenreType.Female, Elo = 1686, Role = User.RoleType.Player },
                new User { Id = 104, Username = "LucasHunt", Email = "lucas.hunt9@boardgames.io", Password = "pwd7210", Birthdate = new DateTime(1985, 4, 18), Genre = User.GenreType.Male, Elo = 2045, Role = User.RoleType.Player },
                new User { Id = 105, Username = "PenelopeHenderson", Email = "penelope.henderson30@strategy.gg", Password = "pwd3442", Birthdate = new DateTime(1997, 12, 22), Genre = User.GenreType.Female, Elo = 1578, Role = User.RoleType.Player },
                new User { Id = 106, Username = "EthanBaker", Email = "ethan.baker21@gmail.com", Password = "pwd2065", Birthdate = new DateTime(1990, 9, 29), Genre = User.GenreType.Male, Elo = 1817, Role = User.RoleType.Player },
                new User { Id = 107, Username = "EthanRobinson", Email = "ethan.robinson18@yahoo.com", Password = "pwd4379", Birthdate = new DateTime(1983, 2, 8), Genre = User.GenreType.Male, Elo = 1967, Role = User.RoleType.Player },
                new User { Id = 108, Username = "LaylaCampbell", Email = "layla.campbell73@outlook.com", Password = "pwd9004", Birthdate = new DateTime(1999, 6, 11), Genre = User.GenreType.Female, Elo = 1234, Role = User.RoleType.Player },
                new User { Id = 109, Username = "AmeliaWhite", Email = "amelia.white50@example.com", Password = "pwd0829", Birthdate = new DateTime(1986, 5, 5), Genre = User.GenreType.Female, Elo = 1975, Role = User.RoleType.Player },
                new User { Id = 110, Username = "MasonPerez", Email = "mason.perez61@mail.com", Password = "pwd6577", Birthdate = new DateTime(1994, 1, 2), Genre = User.GenreType.Male, Elo = 1805, Role = User.RoleType.Player },
                new User { Id = 111, Username = "CamilaGarcia", Email = "camila.garcia26@protonmail.com", Password = "pwd3126", Birthdate = new DateTime(1992, 7, 12), Genre = User.GenreType.Female, Elo = 2159, Role = User.RoleType.Player },
                new User { Id = 112, Username = "LilyLewis", Email = "lily.lewis47@hotmail.com", Password = "pwd4950", Birthdate = new DateTime(1995, 3, 31), Genre = User.GenreType.Female, Elo = 1477, Role = User.RoleType.Player },
                new User { Id = 113, Username = "AmeliaCarter", Email = "amelia.carter8@gamesmail.com", Password = "pwd6274", Birthdate = new DateTime(1998, 10, 13), Genre = User.GenreType.Female, Elo = 1194, Role = User.RoleType.Player },
                new User { Id = 114, Username = "IsabellaJones", Email = "isabella.jones36@playzone.net", Password = "pwd9531", Birthdate = new DateTime(1990, 2, 20), Genre = User.GenreType.Female, Elo = 1366, Role = User.RoleType.Player },
                new User { Id = 115, Username = "LilyNguyen", Email = "lily.nguyen99@chessworld.org", Password = "pwd2107", Birthdate = new DateTime(1993, 8, 27), Genre = User.GenreType.Other, Elo = 1539, Role = User.RoleType.Player },
                new User { Id = 116, Username = "ElijahMartinez", Email = "elijah.martinez4@boardgames.io", Password = "pwd7883", Birthdate = new DateTime(1988, 11, 2), Genre = User.GenreType.Male, Elo = 1933, Role = User.RoleType.Player },
                new User { Id = 117, Username = "AvaCarter", Email = "ava.carter59@strategy.gg", Password = "pwd4632", Birthdate = new DateTime(1996, 6, 25), Genre = User.GenreType.Female, Elo = 1761, Role = User.RoleType.Player },
                new User { Id = 118, Username = "EllaYoung", Email = "ella.young34@gmail.com", Password = "pwd8190", Birthdate = new DateTime(1991, 12, 9), Genre = User.GenreType.Female, Elo = 1620, Role = User.RoleType.Player },
                new User { Id = 119, Username = "ScarlettSmith", Email = "scarlett.smith16@yahoo.com", Password = "pwd2746", Birthdate = new DateTime(1984, 4, 4), Genre = User.GenreType.Female, Elo = 1422, Role = User.RoleType.Player },
                new User { Id = 120, Username = "CaseyJackson", Email = "casey.jackson37@outlook.com", Password = "pwd7065", Birthdate = new DateTime(1997, 11, 30), Genre = User.GenreType.Other, Elo = 1262, Role = User.RoleType.Player },
                new User { Id = 121, Username = "OwenBrooks", Email = "owen.brooks12@example.com", Password = "pwd3907", Birthdate = new DateTime(1990, 8, 8), Genre = User.GenreType.Male, Elo = 1994, Role = User.RoleType.Player },
            ]);

            modelBuilder.Entity<Tournament>().HasData([
                new Tournament {
                    Id = 1,
                    Name = "Open International de Paris",
                    Place = "Paris",
                    MinPlayer = 8,
                    MaxPlayer = 32,
                    NbPlayer = 0,
                    MinElo = 1600,
                    MaxElo = 2800,
                    Category = Tournament.CategoryType.Senior | Tournament.CategoryType.Veteran,
                    Status = Tournament.StatusType.Waiting,
                    WomenOnly = false,
                    CreationDate = new DateTime(2025, 10, 11),
                    LastUpdateDate = new DateTime(2025, 10, 11),
                    CloseDate = new DateTime(2025, 11, 12)
                },
                new Tournament {
                    Id = 2,
                    Name = "Championnat Féminin de Lyon",
                    Place = "Lyon",
                    MinPlayer = 4,
                    MaxPlayer = 16,
                    NbPlayer = 0,
                    MinElo = 1200,
                    MaxElo = 2400,
                    Category = Tournament.CategoryType.Senior,
                    Status = Tournament.StatusType.Waiting,
                    WomenOnly = true,
                    CreationDate = new DateTime(2025, 10, 11),
                    LastUpdateDate = new DateTime(2025, 10, 11),
                    CloseDate = new DateTime(2025, 10, 27)
                },
                new Tournament {
                    Id = 3,
                    Name = "Blitz d’Hiver de Lille",
                    Place = "Lille",
                    MinPlayer = 6,
                    MaxPlayer = 20,
                    NbPlayer = 0,
                    MinElo = 1000,
                    MaxElo = 2200,
                    Category = Tournament.CategoryType.Senior,
                    Status = Tournament.StatusType.Waiting,
                    WomenOnly = false,
                    CreationDate = new DateTime(2025, 10, 11),
                    LastUpdateDate = new DateTime(2025, 10, 11),
                    CloseDate = new DateTime(2025, 10, 31)
                },
                new Tournament {
                    Id = 4,
                    Name = "Tournoi Jeunes Espoirs",
                    Place = "Marseille",
                    MinPlayer = 4,
                    MaxPlayer = 12,
                    NbPlayer = 0,
                    MinElo = 800,
                    MaxElo = 1600,
                    Category = Tournament.CategoryType.Junior,
                    Status = Tournament.StatusType.Waiting,
                    WomenOnly = false,
                    CreationDate = new DateTime(2025, 10, 11),
                    LastUpdateDate = new DateTime(2025, 10, 11),
                    CloseDate = new DateTime(2025, 10, 23)
                },
                new Tournament {
                    Id = 5,
                    Name = "Grand Prix de Bordeaux",
                    Place = "Bordeaux",
                    MinPlayer = 8,
                    MaxPlayer = 24,
                    NbPlayer = 0,
                    MinElo = 1500,
                    MaxElo = 2600,
                    Category = Tournament.CategoryType.Senior | Tournament.CategoryType.Veteran,
                    Status = Tournament.StatusType.Waiting,
                    WomenOnly = false,
                    CreationDate = new DateTime(2025, 10, 11),
                    LastUpdateDate = new DateTime(2025, 10, 11),
                    CloseDate = new DateTime(2025, 11, 4)
                },
                new Tournament {
                    Id = 6,
                    Name = "Open Mixte de Toulouse",
                    Place = "Toulouse",
                    MinPlayer = 6,
                    MaxPlayer = 20,
                    NbPlayer = 0,
                    MinElo = 1300,
                    MaxElo = 2400,
                    Category = Tournament.CategoryType.Senior,
                    Status = Tournament.StatusType.Waiting,
                    WomenOnly = false,
                    CreationDate = new DateTime(2025, 10, 11),
                    LastUpdateDate = new DateTime(2025, 10, 11),
                    CloseDate = new DateTime(2025, 10, 31)
                },
                new Tournament {
                    Id = 7,
                    Name = "Tournoi des Rookies",
                    Place = "Nantes",
                    MinPlayer = 4,
                    MaxPlayer = 16,
                    NbPlayer = 0,
                    MinElo = 0,
                    MaxElo = 1400,
                    Category = Tournament.CategoryType.Junior,
                    Status = Tournament.StatusType.Waiting,
                    WomenOnly = false,
                    CreationDate = new DateTime(2025, 10, 11),
                    LastUpdateDate = new DateTime(2025, 10, 11),
                    CloseDate = new DateTime(2025, 10, 27)
                },
                new Tournament {
                    Id = 8,
                    Name = "Championnat de Bretagne",
                    Place = "Rennes",
                    MinPlayer = 10,
                    MaxPlayer = 32,
                    NbPlayer = 0,
                    MinElo = 1400,
                    MaxElo = 2600,
                    Category = Tournament.CategoryType.Senior,
                    Status = Tournament.StatusType.Waiting,
                    WomenOnly = false,
                    CreationDate = new DateTime(2025, 10, 11),
                    LastUpdateDate = new DateTime(2025, 10, 11),
                    CloseDate = new DateTime(2025, 11, 12)
                },
                new Tournament {
                    Id = 9,
                    Name = "Open Féminin de Nice",
                    Place = "Nice",
                    MinPlayer = 4,
                    MaxPlayer = 20,
                    NbPlayer = 0,
                    MinElo = 1100,
                    MaxElo = 2200,
                    Category = Tournament.CategoryType.Senior | Tournament.CategoryType.Junior,
                    Status = Tournament.StatusType.Waiting,
                    WomenOnly = true,
                    CreationDate = new DateTime(2025, 10, 11),
                    LastUpdateDate = new DateTime(2025, 10, 11),
                    CloseDate = new DateTime(2025, 10, 31)
                },
                new Tournament {
                    Id = 10,
                    Name = "Tournoi Rapide du Capitole",
                    Place = "Toulouse",
                    MinPlayer = 12,
                    MaxPlayer = 28,
                    NbPlayer = 0,
                    MinElo = 1500,
                    MaxElo = 2600,
                    Category = Tournament.CategoryType.Senior,
                    Status = Tournament.StatusType.Waiting,
                    WomenOnly = false,
                    CreationDate = new DateTime(2025, 10, 11),
                    LastUpdateDate = new DateTime(2025, 10, 11),
                    CloseDate = new DateTime(2025, 11, 8)
                },
                new Tournament {
                    Id = 11,
                    Name = "Festival Échecs de Cannes",
                    Place = "Cannes",
                    MinPlayer = 12,
                    MaxPlayer = 32,
                    NbPlayer = 0,
                    MinElo = 1600,
                    MaxElo = 2800,
                    Category = Tournament.CategoryType.Senior | Tournament.CategoryType.Veteran,
                    Status = Tournament.StatusType.Waiting,
                    WomenOnly = false,
                    CreationDate = new DateTime(2025, 10, 11),
                    LastUpdateDate = new DateTime(2025, 10, 11),
                    CloseDate = new DateTime(2025, 11, 12)
                },
                new Tournament {
                    Id = 12,
                    Name = "Open Universitaire de Grenoble",
                    Place = "Grenoble",
                    MinPlayer = 6,
                    MaxPlayer = 24,
                    NbPlayer = 0,
                    MinElo = 1000,
                    MaxElo = 2100,
                    Category = Tournament.CategoryType.Junior,
                    Status = Tournament.StatusType.Waiting,
                    WomenOnly = false,
                    CreationDate = new DateTime(2025, 10, 11),
                    LastUpdateDate = new DateTime(2025, 10, 11),
                    CloseDate = new DateTime(2025, 11, 4)
                },
                new Tournament {
                    Id = 13,
                    Name = "Coupe des Dames",
                    Place = "Strasbourg",
                    MinPlayer = 8,
                    MaxPlayer = 16,
                    NbPlayer = 0,
                    MinElo = 1000,
                    MaxElo = 2500,
                    Category = Tournament.CategoryType.Senior,
                    Status = Tournament.StatusType.Waiting,
                    WomenOnly = true,
                    CreationDate = new DateTime(2025, 10, 11),
                    LastUpdateDate = new DateTime(2025, 10, 11),
                    CloseDate = new DateTime(2025, 10, 27)
                },
                new Tournament {
                    Id = 14,
                    Name = "Tournoi de la Montagne Noire",
                    Place = "Carcassonne",
                    MinPlayer = 8,
                    MaxPlayer = 20,
                    NbPlayer = 0,
                    MinElo = 1300,
                    MaxElo = 2500,
                    Category = Tournament.CategoryType.Veteran,
                    Status = Tournament.StatusType.Waiting,
                    WomenOnly = false,
                    CreationDate = new DateTime(2025, 10, 11),
                    LastUpdateDate = new DateTime(2025, 10, 11),
                    CloseDate = new DateTime(2025, 10, 31)
                },
                new Tournament {
                    Id = 15,
                    Name = "Championnat Régional Jeunes",
                    Place = "Dijon",
                    MinPlayer = 6,
                    MaxPlayer = 16,
                    NbPlayer = 0,
                    MinElo = 800,
                    MaxElo = 1500,
                    Category = Tournament.CategoryType.Junior,
                    Status = Tournament.StatusType.Waiting,
                    WomenOnly = false,
                    CreationDate = new DateTime(2025, 10, 11),
                    LastUpdateDate = new DateTime(2025, 10, 11),
                    CloseDate = new DateTime(2025, 10, 27)
                },
                new Tournament {
                    Id = 16,
                    Name = "Tournoi des Légendes",
                    Place = "Reims",
                    MinPlayer = 8,
                    MaxPlayer = 20,
                    NbPlayer = 0,
                    MinElo = 1500,
                    MaxElo = 2800,
                    Category = Tournament.CategoryType.Veteran,
                    Status = Tournament.StatusType.Waiting,
                    WomenOnly = false,
                    CreationDate = new DateTime(2025, 10, 11),
                    LastUpdateDate = new DateTime(2025, 10, 11),
                    CloseDate = new DateTime(2025, 10, 31)
                },
                new Tournament {
                    Id = 17,
                    Name = "Open de Printemps",
                    Place = "Angers",
                    MinPlayer = 10,
                    MaxPlayer = 32,
                    NbPlayer = 0,
                    MinElo = 1300,
                    MaxElo = 2500,
                    Category = Tournament.CategoryType.Senior | Tournament.CategoryType.Junior,
                    Status = Tournament.StatusType.Waiting,
                    WomenOnly = false,
                    CreationDate = new DateTime(2025, 10, 11),
                    LastUpdateDate = new DateTime(2025, 10, 11),
                    CloseDate = new DateTime(2025, 11, 12)
                },
                new Tournament {
                    Id = 18,
                    Name = "Blitz Féminin de Montpellier",
                    Place = "Montpellier",
                    MinPlayer = 4,
                    MaxPlayer = 16,
                    NbPlayer = 0,
                    MinElo = 1100,
                    MaxElo = 2200,
                    Category = Tournament.CategoryType.Senior,
                    Status = Tournament.StatusType.Waiting,
                    WomenOnly = true,
                    CreationDate = new DateTime(2025, 10, 11),
                    LastUpdateDate = new DateTime(2025, 10, 11),
                    CloseDate = new DateTime(2025, 10, 27)
                },
                new Tournament {
                    Id = 19,
                    Name = "Open National d’Été",
                    Place = "La Rochelle",
                    MinPlayer = 12,
                    MaxPlayer = 28,
                    NbPlayer = 0,
                    MinElo = 1500,
                    MaxElo = 2700,
                    Category = Tournament.CategoryType.Senior | Tournament.CategoryType.Veteran,
                    Status = Tournament.StatusType.Waiting,
                    WomenOnly = false,
                    CreationDate = new DateTime(2025, 10, 11),
                    LastUpdateDate = new DateTime(2025, 10, 11),
                    CloseDate = new DateTime(2025, 11, 8)
                },
                new Tournament {
                    Id = 20,
                    Name = "Open Juniors du Nord",
                    Place = "Lille",
                    MinPlayer = 6,
                    MaxPlayer = 20,
                    NbPlayer = 0,
                    MinElo = 800,
                    MaxElo = 1600,
                    Category = Tournament.CategoryType.Junior,
                    Status = Tournament.StatusType.Waiting,
                    WomenOnly = false,
                    CreationDate = new DateTime(2025, 10, 11),
                    LastUpdateDate = new DateTime(2025, 10, 11),
                    CloseDate = new DateTime(2025, 10, 31)
                }

                ]);


#endif
        }
    }
}
