// <auto-generated />
using System;
using Checkmate;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Checkmate.Migrations
{
    [DbContext(typeof(Chesscontext))]
    [Migration("20251001084420_removeRegistration")]
    partial class removeRegistration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Checkmate.Entity.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CloseDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaxElo")
                        .HasColumnType("int");

                    b.Property<int>("MaxPlayer")
                        .HasColumnType("int");

                    b.Property<int?>("MinElo")
                        .HasColumnType("int");

                    b.Property<int>("MinPlayer")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("WomenOnly")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("Checkmate.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Elo")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Pseudo")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 21,
                            Birthdate = new DateTime(1990, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2859,
                            Email = "nico@chess.com",
                            Genre = 0,
                            Password = "1234",
                            Pseudo = "Nico",
                            Role = 0
                        },
                        new
                        {
                            Id = 1,
                            Birthdate = new DateTime(1990, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2859,
                            Email = "magnus@chess.com",
                            Genre = 0,
                            Password = "1234",
                            Pseudo = "MagnusCarlsen",
                            Role = 1
                        },
                        new
                        {
                            Id = 2,
                            Birthdate = new DateTime(1987, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2787,
                            Email = "hikaru@chess.com",
                            Genre = 0,
                            Password = "1234",
                            Pseudo = "HikaruNakamura",
                            Role = 1
                        },
                        new
                        {
                            Id = 3,
                            Birthdate = new DateTime(1992, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2780,
                            Email = "ding@chess.com",
                            Genre = 0,
                            Password = "1234",
                            Pseudo = "DingLiren",
                            Role = 1
                        },
                        new
                        {
                            Id = 4,
                            Birthdate = new DateTime(1990, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2770,
                            Email = "nepo@chess.com",
                            Genre = 0,
                            Password = "1234",
                            Pseudo = "IanNepomniachtchi",
                            Role = 1
                        },
                        new
                        {
                            Id = 5,
                            Birthdate = new DateTime(1992, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2760,
                            Email = "fabiano@chess.com",
                            Genre = 0,
                            Password = "1234",
                            Pseudo = "FabianoCaruana",
                            Role = 1
                        },
                        new
                        {
                            Id = 6,
                            Birthdate = new DateTime(2003, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2750,
                            Email = "firouzja@chess.com",
                            Genre = 0,
                            Password = "1234",
                            Pseudo = "AlirezaFirouzja",
                            Role = 1
                        },
                        new
                        {
                            Id = 7,
                            Birthdate = new DateTime(1976, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2735,
                            Email = "judit@chess.com",
                            Genre = 1,
                            Password = "1234",
                            Pseudo = "JuditPolgar",
                            Role = 1
                        },
                        new
                        {
                            Id = 8,
                            Birthdate = new DateTime(1994, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2658,
                            Email = "hou@chess.com",
                            Genre = 1,
                            Password = "1234",
                            Pseudo = "HouYifan",
                            Role = 1
                        },
                        new
                        {
                            Id = 9,
                            Birthdate = new DateTime(1943, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2785,
                            Email = "fischer@chess.com",
                            Genre = 0,
                            Password = "1234",
                            Pseudo = "BobbyFischer",
                            Role = 1
                        },
                        new
                        {
                            Id = 10,
                            Birthdate = new DateTime(1963, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2812,
                            Email = "kasparov@chess.com",
                            Genre = 0,
                            Password = "1234",
                            Pseudo = "GarryKasparov",
                            Role = 1
                        },
                        new
                        {
                            Id = 11,
                            Birthdate = new DateTime(1995, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2100,
                            Email = "cm42@chess.com",
                            Genre = 2,
                            Password = "1234",
                            Pseudo = "ChessMaster42",
                            Role = 1
                        },
                        new
                        {
                            Id = 12,
                            Birthdate = new DateTime(1988, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1800,
                            Email = "knight@chess.com",
                            Genre = 0,
                            Password = "1234",
                            Pseudo = "KnightRider",
                            Role = 1
                        },
                        new
                        {
                            Id = 13,
                            Birthdate = new DateTime(1999, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1950,
                            Email = "queen@chess.com",
                            Genre = 1,
                            Password = "1234",
                            Pseudo = "QueenSlayer",
                            Role = 1
                        },
                        new
                        {
                            Id = 14,
                            Birthdate = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1200,
                            Email = "pawn@chess.com",
                            Genre = 0,
                            Password = "1234",
                            Pseudo = "PawnStar",
                            Role = 1
                        },
                        new
                        {
                            Id = 15,
                            Birthdate = new DateTime(1993, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1600,
                            Email = "rook@chess.com",
                            Genre = 2,
                            Password = "1234",
                            Pseudo = "RookAndRoll",
                            Role = 1
                        },
                        new
                        {
                            Id = 16,
                            Birthdate = new DateTime(1985, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2000,
                            Email = "strategist@chess.com",
                            Genre = 0,
                            Password = "1234",
                            Pseudo = "TheStrategist",
                            Role = 1
                        },
                        new
                        {
                            Id = 17,
                            Birthdate = new DateTime(1997, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1750,
                            Email = "blitz@chess.com",
                            Genre = 1,
                            Password = "1234",
                            Pseudo = "BlitzQueen",
                            Role = 1
                        },
                        new
                        {
                            Id = 18,
                            Birthdate = new DateTime(1980, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2200,
                            Email = "checkmate@chess.com",
                            Genre = 0,
                            Password = "1234",
                            Pseudo = "CheckmateKing",
                            Role = 1
                        },
                        new
                        {
                            Id = 19,
                            Birthdate = new DateTime(1992, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2300,
                            Email = "endgame@chess.com",
                            Genre = 0,
                            Password = "1234",
                            Pseudo = "EndgameWizard",
                            Role = 1
                        },
                        new
                        {
                            Id = 20,
                            Birthdate = new DateTime(1998, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1900,
                            Email = "opening@chess.com",
                            Genre = 2,
                            Password = "1234",
                            Pseudo = "OpeningGenius",
                            Role = 1
                        });
                });

            modelBuilder.Entity("TournamentUser", b =>
                {
                    b.Property<int>("RegistrationsId")
                        .HasColumnType("int");

                    b.Property<int>("RegistrationsId1")
                        .HasColumnType("int");

                    b.HasKey("RegistrationsId", "RegistrationsId1");

                    b.HasIndex("RegistrationsId1");

                    b.ToTable("TournamentUser");
                });

            modelBuilder.Entity("TournamentUser", b =>
                {
                    b.HasOne("Checkmate.Entity.Tournament", null)
                        .WithMany()
                        .HasForeignKey("RegistrationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Checkmate.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("RegistrationsId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
