// <auto-generated />
using System;
using Checkmate;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Checkmate.Migrations
{
    [DbContext(typeof(Chesscontext))]
    [Migration("20251105184758_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Checkmate.Entity.Encounter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlackPlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Results")
                        .HasColumnType("int");

                    b.Property<int>("Round")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.Property<int>("WhitePlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BlackPlayerId");

                    b.HasIndex("TournamentId");

                    b.HasIndex("WhitePlayerId");

                    b.ToTable("Encounters");
                });

            modelBuilder.Entity("Checkmate.Entity.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CloseDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaxElo")
                        .HasColumnType("int");

                    b.Property<int>("MaxPlayer")
                        .HasColumnType("int");

                    b.Property<int?>("MinElo")
                        .HasColumnType("int");

                    b.Property<int>("MinPlayer")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NbPlayer")
                        .HasColumnType("int");

                    b.Property<string>("Place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("WomenOnly")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Tournaments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 6,
                            CloseDate = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentRound = 0,
                            LastUpdateDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxElo = 2800,
                            MaxPlayer = 32,
                            MinElo = 1600,
                            MinPlayer = 8,
                            Name = "Open International de Paris",
                            NbPlayer = 0,
                            Place = "Paris",
                            Status = 0,
                            WomenOnly = false
                        },
                        new
                        {
                            Id = 2,
                            Category = 2,
                            CloseDate = new DateTime(2025, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentRound = 0,
                            LastUpdateDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxElo = 2400,
                            MaxPlayer = 16,
                            MinElo = 1200,
                            MinPlayer = 4,
                            Name = "Championnat Féminin de Lyon",
                            NbPlayer = 0,
                            Place = "Lyon",
                            Status = 0,
                            WomenOnly = true
                        },
                        new
                        {
                            Id = 3,
                            Category = 2,
                            CloseDate = new DateTime(2025, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentRound = 0,
                            LastUpdateDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxElo = 2200,
                            MaxPlayer = 20,
                            MinElo = 1000,
                            MinPlayer = 6,
                            Name = "Blitz d’Hiver de Lille",
                            NbPlayer = 0,
                            Place = "Lille",
                            Status = 0,
                            WomenOnly = false
                        },
                        new
                        {
                            Id = 4,
                            Category = 1,
                            CloseDate = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentRound = 0,
                            LastUpdateDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxElo = 1600,
                            MaxPlayer = 12,
                            MinElo = 800,
                            MinPlayer = 4,
                            Name = "Tournoi Jeunes Espoirs",
                            NbPlayer = 0,
                            Place = "Marseille",
                            Status = 0,
                            WomenOnly = false
                        },
                        new
                        {
                            Id = 5,
                            Category = 6,
                            CloseDate = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentRound = 0,
                            LastUpdateDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxElo = 2600,
                            MaxPlayer = 24,
                            MinElo = 1500,
                            MinPlayer = 8,
                            Name = "Grand Prix de Bordeaux",
                            NbPlayer = 0,
                            Place = "Bordeaux",
                            Status = 0,
                            WomenOnly = false
                        },
                        new
                        {
                            Id = 6,
                            Category = 2,
                            CloseDate = new DateTime(2025, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentRound = 0,
                            LastUpdateDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxElo = 2400,
                            MaxPlayer = 20,
                            MinElo = 1300,
                            MinPlayer = 6,
                            Name = "Open Mixte de Toulouse",
                            NbPlayer = 0,
                            Place = "Toulouse",
                            Status = 0,
                            WomenOnly = false
                        },
                        new
                        {
                            Id = 7,
                            Category = 1,
                            CloseDate = new DateTime(2025, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentRound = 0,
                            LastUpdateDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxElo = 1400,
                            MaxPlayer = 16,
                            MinElo = 0,
                            MinPlayer = 4,
                            Name = "Tournoi des Rookies",
                            NbPlayer = 0,
                            Place = "Nantes",
                            Status = 0,
                            WomenOnly = false
                        },
                        new
                        {
                            Id = 8,
                            Category = 2,
                            CloseDate = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentRound = 0,
                            LastUpdateDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxElo = 2600,
                            MaxPlayer = 32,
                            MinElo = 1400,
                            MinPlayer = 10,
                            Name = "Championnat de Bretagne",
                            NbPlayer = 0,
                            Place = "Rennes",
                            Status = 0,
                            WomenOnly = false
                        },
                        new
                        {
                            Id = 9,
                            Category = 3,
                            CloseDate = new DateTime(2025, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentRound = 0,
                            LastUpdateDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxElo = 2200,
                            MaxPlayer = 20,
                            MinElo = 1100,
                            MinPlayer = 4,
                            Name = "Open Féminin de Nice",
                            NbPlayer = 0,
                            Place = "Nice",
                            Status = 0,
                            WomenOnly = true
                        },
                        new
                        {
                            Id = 10,
                            Category = 2,
                            CloseDate = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentRound = 0,
                            LastUpdateDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxElo = 2600,
                            MaxPlayer = 28,
                            MinElo = 1500,
                            MinPlayer = 12,
                            Name = "Tournoi Rapide du Capitole",
                            NbPlayer = 0,
                            Place = "Toulouse",
                            Status = 0,
                            WomenOnly = false
                        },
                        new
                        {
                            Id = 11,
                            Category = 6,
                            CloseDate = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentRound = 0,
                            LastUpdateDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxElo = 2800,
                            MaxPlayer = 32,
                            MinElo = 1600,
                            MinPlayer = 12,
                            Name = "Festival Échecs de Cannes",
                            NbPlayer = 0,
                            Place = "Cannes",
                            Status = 0,
                            WomenOnly = false
                        },
                        new
                        {
                            Id = 12,
                            Category = 1,
                            CloseDate = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentRound = 0,
                            LastUpdateDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxElo = 2100,
                            MaxPlayer = 24,
                            MinElo = 1000,
                            MinPlayer = 6,
                            Name = "Open Universitaire de Grenoble",
                            NbPlayer = 0,
                            Place = "Grenoble",
                            Status = 0,
                            WomenOnly = false
                        },
                        new
                        {
                            Id = 13,
                            Category = 2,
                            CloseDate = new DateTime(2025, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentRound = 0,
                            LastUpdateDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxElo = 2500,
                            MaxPlayer = 16,
                            MinElo = 1000,
                            MinPlayer = 8,
                            Name = "Coupe des Dames",
                            NbPlayer = 0,
                            Place = "Strasbourg",
                            Status = 0,
                            WomenOnly = true
                        },
                        new
                        {
                            Id = 14,
                            Category = 4,
                            CloseDate = new DateTime(2025, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentRound = 0,
                            LastUpdateDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxElo = 2500,
                            MaxPlayer = 20,
                            MinElo = 1300,
                            MinPlayer = 8,
                            Name = "Tournoi de la Montagne Noire",
                            NbPlayer = 0,
                            Place = "Carcassonne",
                            Status = 0,
                            WomenOnly = false
                        },
                        new
                        {
                            Id = 15,
                            Category = 1,
                            CloseDate = new DateTime(2025, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentRound = 0,
                            LastUpdateDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxElo = 1500,
                            MaxPlayer = 16,
                            MinElo = 800,
                            MinPlayer = 6,
                            Name = "Championnat Régional Jeunes",
                            NbPlayer = 0,
                            Place = "Dijon",
                            Status = 0,
                            WomenOnly = false
                        },
                        new
                        {
                            Id = 16,
                            Category = 4,
                            CloseDate = new DateTime(2025, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentRound = 0,
                            LastUpdateDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxElo = 2800,
                            MaxPlayer = 20,
                            MinElo = 1500,
                            MinPlayer = 8,
                            Name = "Tournoi des Légendes",
                            NbPlayer = 0,
                            Place = "Reims",
                            Status = 0,
                            WomenOnly = false
                        },
                        new
                        {
                            Id = 17,
                            Category = 3,
                            CloseDate = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentRound = 0,
                            LastUpdateDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxElo = 2500,
                            MaxPlayer = 32,
                            MinElo = 1300,
                            MinPlayer = 10,
                            Name = "Open de Printemps",
                            NbPlayer = 0,
                            Place = "Angers",
                            Status = 0,
                            WomenOnly = false
                        },
                        new
                        {
                            Id = 18,
                            Category = 2,
                            CloseDate = new DateTime(2025, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentRound = 0,
                            LastUpdateDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxElo = 2200,
                            MaxPlayer = 16,
                            MinElo = 1100,
                            MinPlayer = 4,
                            Name = "Blitz Féminin de Montpellier",
                            NbPlayer = 0,
                            Place = "Montpellier",
                            Status = 0,
                            WomenOnly = true
                        },
                        new
                        {
                            Id = 19,
                            Category = 6,
                            CloseDate = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentRound = 0,
                            LastUpdateDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxElo = 2700,
                            MaxPlayer = 28,
                            MinElo = 1500,
                            MinPlayer = 12,
                            Name = "Open National d’Été",
                            NbPlayer = 0,
                            Place = "La Rochelle",
                            Status = 0,
                            WomenOnly = false
                        },
                        new
                        {
                            Id = 20,
                            Category = 1,
                            CloseDate = new DateTime(2025, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentRound = 0,
                            LastUpdateDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxElo = 1600,
                            MaxPlayer = 20,
                            MinElo = 800,
                            MinPlayer = 6,
                            Name = "Open Juniors du Nord",
                            NbPlayer = 0,
                            Place = "Lille",
                            Status = 0,
                            WomenOnly = false
                        });
                });

            modelBuilder.Entity("Checkmate.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Elo")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 21,
                            Birthdate = new DateTime(1990, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2500,
                            Email = "nico@chess.com",
                            Genre = 0,
                            Password = "123456",
                            Role = 0,
                            Username = "Nico",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 1,
                            Birthdate = new DateTime(1990, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2859,
                            Email = "magnus@chess.com",
                            Genre = 0,
                            Password = "123456",
                            Role = 1,
                            Username = "MagnusCarlsen",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            Birthdate = new DateTime(1987, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2787,
                            Email = "hikaru@chess.com",
                            Genre = 0,
                            Password = "123456",
                            Role = 1,
                            Username = "HikaruNakamura",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            Birthdate = new DateTime(1992, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2780,
                            Email = "ding@chess.com",
                            Genre = 0,
                            Password = "123456",
                            Role = 1,
                            Username = "DingLiren",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            Birthdate = new DateTime(1990, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2770,
                            Email = "nepo@chess.com",
                            Genre = 0,
                            Password = "123456",
                            Role = 1,
                            Username = "IanNepomniachtchi",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            Birthdate = new DateTime(1992, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2760,
                            Email = "fabiano@chess.com",
                            Genre = 0,
                            Password = "123456",
                            Role = 1,
                            Username = "FabianoCaruana",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            Birthdate = new DateTime(2003, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2750,
                            Email = "firouzja@chess.com",
                            Genre = 0,
                            Password = "123456",
                            Role = 1,
                            Username = "AlirezaFirouzja",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 7,
                            Birthdate = new DateTime(1976, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2735,
                            Email = "judit@chess.com",
                            Genre = 1,
                            Password = "123456",
                            Role = 1,
                            Username = "JuditPolgar",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 8,
                            Birthdate = new DateTime(1994, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2658,
                            Email = "hou@chess.com",
                            Genre = 1,
                            Password = "123456",
                            Role = 1,
                            Username = "HouYifan",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 9,
                            Birthdate = new DateTime(1943, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2785,
                            Email = "fischer@chess.com",
                            Genre = 0,
                            Password = "123456",
                            Role = 1,
                            Username = "BobbyFischer",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 10,
                            Birthdate = new DateTime(1963, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2812,
                            Email = "kasparov@chess.com",
                            Genre = 0,
                            Password = "123456",
                            Role = 1,
                            Username = "GarryKasparov",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 11,
                            Birthdate = new DateTime(1995, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2100,
                            Email = "cm42@chess.com",
                            Genre = 2,
                            Password = "123456",
                            Role = 1,
                            Username = "ChessMaster42",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 12,
                            Birthdate = new DateTime(1988, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1800,
                            Email = "knight@chess.com",
                            Genre = 0,
                            Password = "123456",
                            Role = 1,
                            Username = "KnightRider",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 13,
                            Birthdate = new DateTime(1999, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1950,
                            Email = "queen@chess.com",
                            Genre = 1,
                            Password = "123456",
                            Role = 1,
                            Username = "QueenSlayer",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 14,
                            Birthdate = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1200,
                            Email = "pawn@chess.com",
                            Genre = 0,
                            Password = "123456",
                            Role = 1,
                            Username = "PawnStar",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 15,
                            Birthdate = new DateTime(1993, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1600,
                            Email = "rook@chess.com",
                            Genre = 2,
                            Password = "123456",
                            Role = 1,
                            Username = "RookAndRoll",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 16,
                            Birthdate = new DateTime(1985, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2000,
                            Email = "strategist@chess.com",
                            Genre = 0,
                            Password = "123456",
                            Role = 1,
                            Username = "TheStrategist",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 17,
                            Birthdate = new DateTime(1997, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1750,
                            Email = "blitz@chess.com",
                            Genre = 1,
                            Password = "123456",
                            Role = 1,
                            Username = "BlitzQueen",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 18,
                            Birthdate = new DateTime(1980, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2200,
                            Email = "checkmate@chess.com",
                            Genre = 0,
                            Password = "123456",
                            Role = 1,
                            Username = "CheckmateKing",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 19,
                            Birthdate = new DateTime(1992, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2300,
                            Email = "endgame@chess.com",
                            Genre = 0,
                            Password = "123456",
                            Role = 1,
                            Username = "EndgameWizard",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 20,
                            Birthdate = new DateTime(1998, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1900,
                            Email = "opening@chess.com",
                            Genre = 2,
                            Password = "123456",
                            Role = 1,
                            Username = "OpeningGenius",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 22,
                            Birthdate = new DateTime(1991, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1620,
                            Email = "alex.martin22@gmail.com",
                            Genre = 0,
                            Password = "pwd4821",
                            Role = 1,
                            Username = "AlexMartin",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 23,
                            Birthdate = new DateTime(1986, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1475,
                            Email = "sam.garcia7@yahoo.com",
                            Genre = 2,
                            Password = "pwd3012",
                            Role = 1,
                            Username = "SamGarcia",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 24,
                            Birthdate = new DateTime(1999, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1540,
                            Email = "taylor.lopez13@outlook.com",
                            Genre = 1,
                            Password = "pwd6543",
                            Role = 1,
                            Username = "TaylorLopez",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 25,
                            Birthdate = new DateTime(1979, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1825,
                            Email = "jordan.johnson41@example.com",
                            Genre = 0,
                            Password = "pwd7730",
                            Role = 1,
                            Username = "JordanJohnson",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 26,
                            Birthdate = new DateTime(2002, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1360,
                            Email = "morgan.smith5@mail.com",
                            Genre = 1,
                            Password = "pwd1904",
                            Role = 1,
                            Username = "MorganSmith",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 27,
                            Birthdate = new DateTime(1983, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1588,
                            Email = "casey.brown99@protonmail.com",
                            Genre = 2,
                            Password = "pwd5882",
                            Role = 1,
                            Username = "CaseyBrown",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 28,
                            Birthdate = new DateTime(1994, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1710,
                            Email = "drew.williams8@hotmail.com",
                            Genre = 0,
                            Password = "pwd4127",
                            Role = 1,
                            Username = "DrewWilliams",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 29,
                            Birthdate = new DateTime(1996, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1395,
                            Email = "evelyn.jones2@gamesmail.com",
                            Genre = 1,
                            Password = "pwd2256",
                            Role = 1,
                            Username = "EvelynJones",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 30,
                            Birthdate = new DateTime(1990, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1987,
                            Email = "liam.miller17@playzone.net",
                            Genre = 0,
                            Password = "pwd8341",
                            Role = 1,
                            Username = "LiamMiller",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 31,
                            Birthdate = new DateTime(2001, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1280,
                            Email = "noah.davis4@chessworld.org",
                            Genre = 0,
                            Password = "pwd0192",
                            Role = 1,
                            Username = "NoahDavis",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 32,
                            Birthdate = new DateTime(1987, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2035,
                            Email = "oliver.wilson61@boardgames.io",
                            Genre = 0,
                            Password = "pwd7723",
                            Role = 1,
                            Username = "OliverWilson",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 33,
                            Birthdate = new DateTime(1998, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1762,
                            Email = "elijah.anderson12@strategy.gg",
                            Genre = 0,
                            Password = "pwd9406",
                            Role = 1,
                            Username = "ElijahAnderson",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 34,
                            Birthdate = new DateTime(1975, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2100,
                            Email = "james.thomas3@gmail.com",
                            Genre = 0,
                            Password = "pwd2675",
                            Role = 1,
                            Username = "JamesThomas",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 35,
                            Birthdate = new DateTime(1993, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1427,
                            Email = "benjamin.taylor88@yahoo.com",
                            Genre = 0,
                            Password = "pwd3819",
                            Role = 1,
                            Username = "BenjaminTaylor",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 36,
                            Birthdate = new DateTime(1989, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1674,
                            Email = "lucas.moore47@outlook.com",
                            Genre = 0,
                            Password = "pwd6654",
                            Role = 1,
                            Username = "LucasMoore",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 37,
                            Birthdate = new DateTime(1997, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1511,
                            Email = "mason.jackson20@example.com",
                            Genre = 0,
                            Password = "pwd5580",
                            Role = 1,
                            Username = "MasonJackson",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 38,
                            Birthdate = new DateTime(1995, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1799,
                            Email = "logan.white66@mail.com",
                            Genre = 2,
                            Password = "pwd1033",
                            Role = 1,
                            Username = "LoganWhite",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 39,
                            Birthdate = new DateTime(1984, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1865,
                            Email = "ethan.harris13@protonmail.com",
                            Genre = 0,
                            Password = "pwd4545",
                            Role = 1,
                            Username = "EthanHarris",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 40,
                            Birthdate = new DateTime(2000, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1322,
                            Email = "ava.thompson31@hotmail.com",
                            Genre = 1,
                            Password = "pwd2880",
                            Role = 1,
                            Username = "AvaThompson",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 41,
                            Birthdate = new DateTime(1992, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1703,
                            Email = "sophia.martinez55@gamesmail.com",
                            Genre = 1,
                            Password = "pwd7201",
                            Role = 1,
                            Username = "SophiaMartinez",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 42,
                            Birthdate = new DateTime(1994, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1609,
                            Email = "isabella.robinson9@playzone.net",
                            Genre = 1,
                            Password = "pwd4419",
                            Role = 1,
                            Username = "IsabellaRobinson",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 43,
                            Birthdate = new DateTime(2003, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1199,
                            Email = "mia.clark77@chessworld.org",
                            Genre = 1,
                            Password = "pwd5310",
                            Role = 1,
                            Username = "MiaClark",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 44,
                            Birthdate = new DateTime(1982, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1890,
                            Email = "amelia.rodriguez2@boardgames.io",
                            Genre = 1,
                            Password = "pwd6752",
                            Role = 1,
                            Username = "AmeliaRodriguez",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 45,
                            Birthdate = new DateTime(1990, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1555,
                            Email = "harper.lewis14@strategy.gg",
                            Genre = 2,
                            Password = "pwd9944",
                            Role = 1,
                            Username = "HarperLewis",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 46,
                            Birthdate = new DateTime(1988, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2001,
                            Email = "charlotte.lee5@gmail.com",
                            Genre = 1,
                            Password = "pwd2168",
                            Role = 1,
                            Username = "CharlotteLee",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 47,
                            Birthdate = new DateTime(1996, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1448,
                            Email = "zoey.walker42@yahoo.com",
                            Genre = 1,
                            Password = "pwd3478",
                            Role = 1,
                            Username = "ZoeyWalker",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 48,
                            Birthdate = new DateTime(1981, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2160,
                            Email = "grace.hall23@outlook.com",
                            Genre = 1,
                            Password = "pwd8110",
                            Role = 1,
                            Username = "GraceHall",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 49,
                            Birthdate = new DateTime(2004, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1015,
                            Email = "luna.allen90@example.com",
                            Genre = 1,
                            Password = "pwd9722",
                            Role = 1,
                            Username = "LunaAllen",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 50,
                            Birthdate = new DateTime(1999, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1491,
                            Email = "camila.young58@mail.com",
                            Genre = 1,
                            Password = "pwd1567",
                            Role = 1,
                            Username = "CamilaYoung",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 51,
                            Birthdate = new DateTime(1997, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1734,
                            Email = "aria.king6@protonmail.com",
                            Genre = 1,
                            Password = "pwd6633",
                            Role = 1,
                            Username = "AriaKing",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 52,
                            Birthdate = new DateTime(1993, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1452,
                            Email = "ella.wright1@hotmail.com",
                            Genre = 1,
                            Password = "pwd4870",
                            Role = 1,
                            Username = "EllaWright",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 53,
                            Birthdate = new DateTime(1985, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1996,
                            Email = "scarlett.scott33@gamesmail.com",
                            Genre = 1,
                            Password = "pwd3355",
                            Role = 1,
                            Username = "ScarlettScott",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 54,
                            Birthdate = new DateTime(1991, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1768,
                            Email = "victoria.torres71@playzone.net",
                            Genre = 1,
                            Password = "pwd9087",
                            Role = 1,
                            Username = "VictoriaTorres",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 55,
                            Birthdate = new DateTime(2000, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1376,
                            Email = "riley.nguyen44@chessworld.org",
                            Genre = 2,
                            Password = "pwd2299",
                            Role = 1,
                            Username = "RileyNguyen",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 56,
                            Birthdate = new DateTime(1980, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2112,
                            Email = "nora.hill18@boardgames.io",
                            Genre = 1,
                            Password = "pwd5501",
                            Role = 1,
                            Username = "NoraHill",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 57,
                            Birthdate = new DateTime(1992, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1681,
                            Email = "hazel.flores8@strategy.gg",
                            Genre = 1,
                            Password = "pwd7812",
                            Role = 1,
                            Username = "HazelFlores",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 58,
                            Birthdate = new DateTime(1998, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1523,
                            Email = "chloe.green69@gmail.com",
                            Genre = 1,
                            Password = "pwd0049",
                            Role = 1,
                            Username = "ChloeGreen",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 59,
                            Birthdate = new DateTime(1996, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1407,
                            Email = "lily.adams27@yahoo.com",
                            Genre = 1,
                            Password = "pwd2783",
                            Role = 1,
                            Username = "LilyAdams",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 60,
                            Birthdate = new DateTime(1987, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1837,
                            Email = "penelope.nelson3@outlook.com",
                            Genre = 1,
                            Password = "pwd6195",
                            Role = 1,
                            Username = "PenelopeNelson",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 61,
                            Birthdate = new DateTime(2005, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 925,
                            Email = "layla.baker52@example.com",
                            Genre = 1,
                            Password = "pwd8320",
                            Role = 1,
                            Username = "LaylaBaker",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 62,
                            Birthdate = new DateTime(1994, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1570,
                            Email = "zoe.hernandez29@mail.com",
                            Genre = 1,
                            Password = "pwd1436",
                            Role = 1,
                            Username = "ZoeHernandez",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 63,
                            Birthdate = new DateTime(1990, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1908,
                            Email = "layla.rivera64@protonmail.com",
                            Genre = 2,
                            Password = "pwd9902",
                            Role = 1,
                            Username = "LaylaRivera",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 64,
                            Birthdate = new DateTime(1989, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1775,
                            Email = "camila.campbell11@hotmail.com",
                            Genre = 1,
                            Password = "pwd4646",
                            Role = 1,
                            Username = "CamilaCampbell",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 65,
                            Birthdate = new DateTime(1995, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1328,
                            Email = "ella.mitchell39@gamesmail.com",
                            Genre = 1,
                            Password = "pwd2057",
                            Role = 1,
                            Username = "EllaMitchell",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 66,
                            Birthdate = new DateTime(1992, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1897,
                            Email = "liam.carter72@playzone.net",
                            Genre = 0,
                            Password = "pwd7129",
                            Role = 1,
                            Username = "LiamCarter",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 67,
                            Birthdate = new DateTime(1986, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2050,
                            Email = "noah.roberts45@chessworld.org",
                            Genre = 0,
                            Password = "pwd3771",
                            Role = 1,
                            Username = "NoahRoberts",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 68,
                            Birthdate = new DateTime(2001, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1215,
                            Email = "oliver.perez9@boardgames.io",
                            Genre = 0,
                            Password = "pwd5566",
                            Role = 1,
                            Username = "OliverPerez",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 69,
                            Birthdate = new DateTime(1999, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1504,
                            Email = "elijah.collins23@strategy.gg",
                            Genre = 0,
                            Password = "pwd8460",
                            Role = 1,
                            Username = "ElijahCollins",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 70,
                            Birthdate = new DateTime(1984, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2228,
                            Email = "james.stewart2@gmail.com",
                            Genre = 0,
                            Password = "pwd3918",
                            Role = 1,
                            Username = "JamesStewart",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 71,
                            Birthdate = new DateTime(1991, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1637,
                            Email = "benjamin.morris14@yahoo.com",
                            Genre = 0,
                            Password = "pwd2734",
                            Role = 1,
                            Username = "BenjaminMorris",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 72,
                            Birthdate = new DateTime(1988, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1748,
                            Email = "lucas.rogers57@outlook.com",
                            Genre = 0,
                            Password = "pwd6032",
                            Role = 1,
                            Username = "LucasRogers",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 73,
                            Birthdate = new DateTime(1996, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1416,
                            Email = "mason.reed81@example.com",
                            Genre = 0,
                            Password = "pwd4859",
                            Role = 1,
                            Username = "MasonReed",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 74,
                            Birthdate = new DateTime(1990, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1979,
                            Email = "logan.cook33@mail.com",
                            Genre = 0,
                            Password = "pwd9220",
                            Role = 1,
                            Username = "LoganCook",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 75,
                            Birthdate = new DateTime(1982, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2093,
                            Email = "ethan.bell28@protonmail.com",
                            Genre = 0,
                            Password = "pwd1582",
                            Role = 1,
                            Username = "EthanBell",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 76,
                            Birthdate = new DateTime(1997, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1345,
                            Email = "ava.murphy46@hotmail.com",
                            Genre = 1,
                            Password = "pwd3376",
                            Role = 1,
                            Username = "AvaMurphy",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 77,
                            Birthdate = new DateTime(1993, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1707,
                            Email = "sophia.bailey60@gamesmail.com",
                            Genre = 1,
                            Password = "pwd7641",
                            Role = 1,
                            Username = "SophiaBailey",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 78,
                            Birthdate = new DateTime(1990, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1881,
                            Email = "isabella.rivera38@playzone.net",
                            Genre = 1,
                            Password = "pwd0584",
                            Role = 1,
                            Username = "IsabellaRivera",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 79,
                            Birthdate = new DateTime(2002, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1247,
                            Email = "mia.cooper5@chessworld.org",
                            Genre = 1,
                            Password = "pwd4810",
                            Role = 1,
                            Username = "MiaCooper",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 80,
                            Birthdate = new DateTime(1985, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2017,
                            Email = "amelia.peterson70@boardgames.io",
                            Genre = 1,
                            Password = "pwd9123",
                            Role = 1,
                            Username = "AmeliaPeterson",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 81,
                            Birthdate = new DateTime(1998, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1399,
                            Email = "harper.gray26@strategy.gg",
                            Genre = 2,
                            Password = "pwd6408",
                            Role = 1,
                            Username = "HarperGray",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 82,
                            Birthdate = new DateTime(1994, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1669,
                            Email = "charlotte.james2@gmail.com",
                            Genre = 1,
                            Password = "pwd2841",
                            Role = 1,
                            Username = "CharlotteJames",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 83,
                            Birthdate = new DateTime(2000, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1256,
                            Email = "zoey.watson49@yahoo.com",
                            Genre = 1,
                            Password = "pwd5027",
                            Role = 1,
                            Username = "ZoeyWatson",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 84,
                            Birthdate = new DateTime(1986, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1872,
                            Email = "grace.brooks31@outlook.com",
                            Genre = 1,
                            Password = "pwd7789",
                            Role = 1,
                            Username = "GraceBrooks",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 85,
                            Birthdate = new DateTime(2004, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 968,
                            Email = "luna.kelly8@example.com",
                            Genre = 1,
                            Password = "pwd3902",
                            Role = 1,
                            Username = "LunaKelly",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 86,
                            Birthdate = new DateTime(1991, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1530,
                            Email = "camila.sanders12@mail.com",
                            Genre = 1,
                            Password = "pwd1478",
                            Role = 1,
                            Username = "CamilaSanders",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 87,
                            Birthdate = new DateTime(1997, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1694,
                            Email = "aria.price56@protonmail.com",
                            Genre = 1,
                            Password = "pwd5514",
                            Role = 1,
                            Username = "AriaPrice",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 88,
                            Birthdate = new DateTime(1995, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1482,
                            Email = "ella.bennett95@hotmail.com",
                            Genre = 1,
                            Password = "pwd8686",
                            Role = 1,
                            Username = "EllaBennett",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 89,
                            Birthdate = new DateTime(1983, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2039,
                            Email = "scarlett.gray21@gamesmail.com",
                            Genre = 1,
                            Password = "pwd3244",
                            Role = 1,
                            Username = "ScarlettGray",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 90,
                            Birthdate = new DateTime(1992, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1759,
                            Email = "victoria.russell7@playzone.net",
                            Genre = 1,
                            Password = "pwd7011",
                            Role = 1,
                            Username = "VictoriaRussell",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 91,
                            Birthdate = new DateTime(1999, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1369,
                            Email = "riley.ortiz40@chessworld.org",
                            Genre = 2,
                            Password = "pwd4398",
                            Role = 1,
                            Username = "RileyOrtiz",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 92,
                            Birthdate = new DateTime(1981, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2144,
                            Email = "nora.gutierrez6@boardgames.io",
                            Genre = 1,
                            Password = "pwd9555",
                            Role = 1,
                            Username = "NoraGutierrez",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 93,
                            Birthdate = new DateTime(1993, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1716,
                            Email = "hazel.ramirez63@strategy.gg",
                            Genre = 1,
                            Password = "pwd2689",
                            Role = 1,
                            Username = "HazelRamirez",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 94,
                            Birthdate = new DateTime(1996, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1526,
                            Email = "chloe.watkins19@gmail.com",
                            Genre = 1,
                            Password = "pwd3840",
                            Role = 1,
                            Username = "ChloeWatkins",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 95,
                            Birthdate = new DateTime(1998, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1410,
                            Email = "lily.webb85@yahoo.com",
                            Genre = 1,
                            Password = "pwd4751",
                            Role = 1,
                            Username = "LilyWebb",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 96,
                            Birthdate = new DateTime(1989, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1850,
                            Email = "penelope.santos34@outlook.com",
                            Genre = 1,
                            Password = "pwd8920",
                            Role = 1,
                            Username = "PenelopeSantos",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 97,
                            Birthdate = new DateTime(2005, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 908,
                            Email = "layla.perry24@example.com",
                            Genre = 1,
                            Password = "pwd6147",
                            Role = 1,
                            Username = "LaylaPerry",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 98,
                            Birthdate = new DateTime(1994, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1569,
                            Email = "zoe.powell2@mail.com",
                            Genre = 1,
                            Password = "pwd7563",
                            Role = 1,
                            Username = "ZoePowell",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 99,
                            Birthdate = new DateTime(1990, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1914,
                            Email = "alex.long67@protonmail.com",
                            Genre = 0,
                            Password = "pwd0825",
                            Role = 1,
                            Username = "AlexLong",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 100,
                            Birthdate = new DateTime(1987, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1602,
                            Email = "casey.patterson44@hotmail.com",
                            Genre = 2,
                            Password = "pwd4991",
                            Role = 1,
                            Username = "CaseyPatterson",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 101,
                            Birthdate = new DateTime(1992, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1771,
                            Email = "drew.reynolds38@gamesmail.com",
                            Genre = 0,
                            Password = "pwd1338",
                            Role = 1,
                            Username = "DrewReynolds",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 102,
                            Birthdate = new DateTime(1996, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1497,
                            Email = "noah.fisher10@playzone.net",
                            Genre = 0,
                            Password = "pwd2886",
                            Role = 1,
                            Username = "NoahFisher",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 103,
                            Birthdate = new DateTime(1991, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1686,
                            Email = "isabella.baker55@chessworld.org",
                            Genre = 1,
                            Password = "pwd5511",
                            Role = 1,
                            Username = "IsabellaBaker",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 104,
                            Birthdate = new DateTime(1985, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2045,
                            Email = "lucas.hunt9@boardgames.io",
                            Genre = 0,
                            Password = "pwd7210",
                            Role = 1,
                            Username = "LucasHunt",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 105,
                            Birthdate = new DateTime(1997, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1578,
                            Email = "penelope.henderson30@strategy.gg",
                            Genre = 1,
                            Password = "pwd3442",
                            Role = 1,
                            Username = "PenelopeHenderson",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 106,
                            Birthdate = new DateTime(1990, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1817,
                            Email = "ethan.baker21@gmail.com",
                            Genre = 0,
                            Password = "pwd2065",
                            Role = 1,
                            Username = "EthanBaker",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 107,
                            Birthdate = new DateTime(1983, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1967,
                            Email = "ethan.robinson18@yahoo.com",
                            Genre = 0,
                            Password = "pwd4379",
                            Role = 1,
                            Username = "EthanRobinson",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 108,
                            Birthdate = new DateTime(1999, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1234,
                            Email = "layla.campbell73@outlook.com",
                            Genre = 1,
                            Password = "pwd9004",
                            Role = 1,
                            Username = "LaylaCampbell",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 109,
                            Birthdate = new DateTime(1986, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1975,
                            Email = "amelia.white50@example.com",
                            Genre = 1,
                            Password = "pwd0829",
                            Role = 1,
                            Username = "AmeliaWhite",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 110,
                            Birthdate = new DateTime(1994, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1805,
                            Email = "mason.perez61@mail.com",
                            Genre = 0,
                            Password = "pwd6577",
                            Role = 1,
                            Username = "MasonPerez",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 111,
                            Birthdate = new DateTime(1992, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 2159,
                            Email = "camila.garcia26@protonmail.com",
                            Genre = 1,
                            Password = "pwd3126",
                            Role = 1,
                            Username = "CamilaGarcia",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 112,
                            Birthdate = new DateTime(1995, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1477,
                            Email = "lily.lewis47@hotmail.com",
                            Genre = 1,
                            Password = "pwd4950",
                            Role = 1,
                            Username = "LilyLewis",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 113,
                            Birthdate = new DateTime(1998, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1194,
                            Email = "amelia.carter8@gamesmail.com",
                            Genre = 1,
                            Password = "pwd6274",
                            Role = 1,
                            Username = "AmeliaCarter",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 114,
                            Birthdate = new DateTime(1990, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1366,
                            Email = "isabella.jones36@playzone.net",
                            Genre = 1,
                            Password = "pwd9531",
                            Role = 1,
                            Username = "IsabellaJones",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 115,
                            Birthdate = new DateTime(1993, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1539,
                            Email = "lily.nguyen99@chessworld.org",
                            Genre = 2,
                            Password = "pwd2107",
                            Role = 1,
                            Username = "LilyNguyen",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 116,
                            Birthdate = new DateTime(1988, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1933,
                            Email = "elijah.martinez4@boardgames.io",
                            Genre = 0,
                            Password = "pwd7883",
                            Role = 1,
                            Username = "ElijahMartinez",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 117,
                            Birthdate = new DateTime(1996, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1761,
                            Email = "ava.carter59@strategy.gg",
                            Genre = 1,
                            Password = "pwd4632",
                            Role = 1,
                            Username = "AvaCarter",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 118,
                            Birthdate = new DateTime(1991, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1620,
                            Email = "ella.young34@gmail.com",
                            Genre = 1,
                            Password = "pwd8190",
                            Role = 1,
                            Username = "EllaYoung",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 119,
                            Birthdate = new DateTime(1984, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1422,
                            Email = "scarlett.smith16@yahoo.com",
                            Genre = 1,
                            Password = "pwd2746",
                            Role = 1,
                            Username = "ScarlettSmith",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 120,
                            Birthdate = new DateTime(1997, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1262,
                            Email = "casey.jackson37@outlook.com",
                            Genre = 2,
                            Password = "pwd7065",
                            Role = 1,
                            Username = "CaseyJackson",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 121,
                            Birthdate = new DateTime(1990, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Elo = 1994,
                            Email = "owen.brooks12@example.com",
                            Genre = 0,
                            Password = "pwd3907",
                            Role = 1,
                            Username = "OwenBrooks",
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("TournamentUser", b =>
                {
                    b.Property<int>("RegistrationsId")
                        .HasColumnType("int");

                    b.Property<int>("RegistrationsId1")
                        .HasColumnType("int");

                    b.HasKey("RegistrationsId", "RegistrationsId1");

                    b.HasIndex("RegistrationsId1");

                    b.ToTable("TournamentUser");
                });

            modelBuilder.Entity("Checkmate.Entity.Encounter", b =>
                {
                    b.HasOne("Checkmate.Entity.User", "BlackPlayer")
                        .WithMany()
                        .HasForeignKey("BlackPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Checkmate.Entity.Tournament", null)
                        .WithMany("Encounters")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Checkmate.Entity.User", "WhitePlayer")
                        .WithMany()
                        .HasForeignKey("WhitePlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BlackPlayer");

                    b.Navigation("WhitePlayer");
                });

            modelBuilder.Entity("TournamentUser", b =>
                {
                    b.HasOne("Checkmate.Entity.Tournament", null)
                        .WithMany()
                        .HasForeignKey("RegistrationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Checkmate.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("RegistrationsId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Checkmate.Entity.Tournament", b =>
                {
                    b.Navigation("Encounters");
                });
#pragma warning restore 612, 618
        }
    }
}
